### PR TITLE
Expand user information when multiple users are followed

### PR DESCRIPTION
**Pull request by aviskarkc10**
* Expand user information when multiple users are followed
* Decrease font size of followed user's name

### CODE REVIEW

**Comment by mesaugat** [comment]
Thank you @aviskarkc10 

Can you upload a screenshot of how it looks after the change?

**Comment by aviskarkc10** [comment]
Before we expand:
image

This is after expanding:
image

**Comment by mesaugat** [comment]
Sadness. We need to decrease the font size of the name, then we should be fine. I remember tweaking it before.

**Comment by aviskarkc10** [comment]
Here is how it looks now
image

**Comment by mesaugat** [comment]
@aviskarkc10 LGTM 💯

**Review by mesaugat — APPROVED** [review]

**Pull request merged**
